# Generated by Django 3.2.8 on 2021-11-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='history',
        ),
    ]
