# Generated by Django 3.2.8 on 2021-11-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_remove_device_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='active',
        ),
        migrations.AddField(
            model_name='device',
            name='patient_id',
            field=models.IntegerField(null=True),
        ),
    ]
