# Generated by Django 3.2.8 on 2021-11-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20211108_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='patient_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
