# Generated by Django 3.2.8 on 2021-11-10 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_device_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregroup',
            name='admin_email',
        ),
        migrations.RemoveField(
            model_name='device',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='caregroup',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caregroup_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_patient', to='sensors.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_device', to='sensors.device'),
        ),
    ]
