# Generated by Django 3.2.8 on 2021-11-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_alter_caregroup_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='caregroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.caregroup'),
        ),
    ]
